config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :pages
  end

  resources :pages do
    resources :comments
  end
  
  resources :pages
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :page
  validates :author, presence: true
  validates :content, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
  has_rich_text :body
  has_many :comments, dependent: :destroy
end

app/controllers/admin/pages_controller.rb
# frozen_string_literal: true

module Admin
  # Controller for managing pages for admin
  class PagesController < ApplicationController
    layout 'admin'
    before_action :find_page_by_id, only: %i[show edit update destroy]
    before_action :authenticate

    def index
      @pages = Page.all
    end

    def show
      @comments = @page.comments
    end

    def new
      @page = Page.new
    end

    def create
      @page = Page.new(page_params)
      if @page.save
        redirect_to admin_pages_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @page.update(page_params)
        redirect_to admin_page_path(@page)
      else
        render :edit
      end
    end

    def destroy
      @page.destroy
      redirect_to admin_pages_path
    end

    private

    def page_params
      params.require(:page).permit(:title, :body)
    end

    def find_page_by_id
      @page = Page.find(params[:id])
    end

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV['ADMIN_USERNAME'] && password == ENV['ADMIN_PASSWORD']
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# Controller for managing comments
class CommentsController < ApplicationController
  before_action :find_page_by_id, only: %i[new create destroy]

  def new
    @comment = @page.comments.new
  end

  def create
    @comment = @page.comments.new(comment_params)

    if @comment.save
      redirect_to @page
    else
      @comments = @page.comments
      render 'pages/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_page_path(@page)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :content)
  end

  def find_page_by_id
    @page = Page.find(params[:page_id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Controller for managing pages for users
class PagesController < ApplicationController
  before_action :initialize_comment, only: %i[index show]
  def index
    @page = Page.find(1)
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
    @comments = @page.comments
  end

  private

  def initialize_comment
    @comment = Comment.new
  end
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/pages/edit.html.erb
<div class="main">
<%= link_to 'Back', admin_pages_path %>
<%= form_with model: [:admin, @page], html: { class: 'page-form' } do |page| %>
  <div class="form-group">
    <%= page.label :title %><br>
    <%= page.text_field :title, class: 'form-control title-control' %>
  </div>
  
  <div class="form-group">
    <%= page.label :body %><br>
    <%= page.rich_text_area :body, class: 'form-control rich-text-area' %>
  </div>
  
  <div>
    <%= page.submit 'Save', class: 'btn btn-submit' %>
  </div>
<% end %>
</div>

app/views/admin/pages/index.html.erb
<div class="main">
<h1>Pages</h1>
<%= link_to 'New page', new_admin_page_path %>
<table >
  <tr>
    <th>Title</th>
    <th>Page</th>
  </tr>
  <% @pages.each do |page| %>
    <tr>
      <td><%= page.title %></td>
      <td>
        <%= link_to 'See', admin_page_path(page), class: "link" %>
        <%= link_to 'Edit', edit_admin_page_path(page), class: "link"  %>
        <%= button_to 'Delete', admin_page_path(page), method: :delete, class: "delete-page" %>
      </td>
    </tr>
  <% end %>
</table>
</div>

app/views/admin/pages/new.html.erb
<div class="main">
<%= link_to 'Back', admin_pages_path %>
<%= form_with model: [:admin, @page], html: { class: 'page-form' } do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_area :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.rich_text_area :body, class: 'form-control' %>
  </div>

  <%= form.submit 'Save', class: 'btn btn-submit' %>
<% end %>
</div>

app/views/admin/pages/show.html.erb
<h1><%= @page.title %></h1>
<p><%= @page.body %></p>
<%= link_to 'Back', admin_pages_path %>

<h2>Comments:</h2>
<div class="comments">
  <% @comments.each do |form| %>
  <table>
    <td><%= button_to 'delete', [@page, form], method: :delete, class: "delete-btn" %><th><%= form.author %>: <%= form.content %></th></td>
  </table>
  <% end %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "admin", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <header>
      <div>
      <h2 class="link">Admin panel <%= link_to 'Back to site', pages_path, class: "link" %></h2>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <header>
<% @pages = Page.all %>
      <% @pages.each do |page| %>
        <ul>
        <li><%= link_to page.title, page_path(page), class: "link"%></li>
        </ul>
      <% end %>
      <h3 class="name"><%= link_to 'Smerch24', 'https://github.com/Smerch24', class: "name"%></h2>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="main">
  <div class="title"><%= @page.title %></div>
  <div class="body"><%= @page.body %></div>
</div>

<hr>

<h2>Add comment:</h2>
<%= form_with(model: [@page, @comment]) do |form| %>
  <div><%= form.label :author %></div>
  <div><%= form.text_field :author, class: "field author-field" %></div>
  <br>
  <div><%= form.label :content %></div>
  <div><%= form.text_field :content, class: "field" %></div>

  <div class="btn-field">
    <%= form.submit 'Submit', class: "btn" %>
  </div>
<% end %>

<div class="comments">
  <% if @comments.present? %>
    <% @comments.each do |form| %>
      <% if form.author.present? && form.content.present? %>
        <h2><%= form.author %>: <%= form.content %></h2>
      <% end %>
    <% end %> 
  <% else %>
    <p>No comments yet.</p>
  <% end %>
</div>

app/views/pages/show.html.erb
<div class="main">
  <div class="title"><%= @page.title %></div>
  <div class="body"><%= @page.body %></div>
</div>

<hr>

<h2>Add comment:</h2>
<%= form_with(model: [@page, @comment]) do |form| %>
  <div><%= form.label :author %></div>
  <div><%= form.text_field :author, class: "field author-field" %></div>
  <br>
  <div><%= form.label :content %></div>
  <div><%= form.text_field :content, class: "field" %></div>

  <div class="btn-field">
    <%= form.submit 'Submit', class: "btn" %>
  </div>
<% end %>

<div class="comments">
  <% if @comments.any? %>
    <% @comments.each do |form| %>
      <% if form.author.present? && form.content.present? %>
        <h2><%= form.author %>: <%= form.content %></h2>
      <% end %>
    <% end %> 
  <% else %>
    <p>No comments yet.</p>
  <% end %>
</div>